spring.application.name=orchid-management
# ===== Server =====
server.port=8005

# ===== SQL Server =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OrchidDBJWT;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Lab6_DB_Password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===== JWT =====
# Secret key phải đủ dài (≥ 256-bit).
# Tạo secret key bằng terminal: openssl rand -hex 32
# copy mã tạo ra vào key
application.security.jwt.secret-key=14c6bbf8f478fdb1b1987db1b55c17b9ba95b04c2bc172eb587e5020d3c0ab39
# 86400000ms = 24h
application.security.jwt.expiration=86400000 
